dist: bionic
language: python
python: "3.8"

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  # Prepare directory for the toolchain
  - mkdir -p ~/esp
  - cd ~/esp
  # Download binary toolchain for the ESP32
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  # Make xtensa-esp32-elf available for all terminal sessions
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  # Get ESP-IDF from github
  - git clone --recursive --branch v3.3 --single-branch --shallow-submodules https://github.com/espressif/esp-idf.git
  # Set the path to ESP-IDF directory
  - export IDF_PATH=~/esp/esp-idf
  # Install python dependencies
  - pip install --requirement $IDF_PATH/requirements.txt

script:
  # Build project within the original repository
  - cd $PROJECT_PATH
  - $IDF_PATH/tools/idf.py build
